common:
    lid_topic: "/os_cloud_node_merged"
    imu_topic: "/imu_vn_100/imu"
    
    time_sync_en: false            # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: -0.1 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                   # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
    
preprocess:
    lidar_type: 3                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line:  128
    timestamp_unit: 3            # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 0.5

mapping:
    # acc_cov: 0.1
    # gyr_cov: 0.1
    # b_acc_cov: 0.0001
    # b_gyr_cov: 0.0001
    # fov_degree: 180
    # det_range:  150.0
    acc_cov: 6.0e-2
    gyr_cov: 5.0e-3
    b_acc_cov: 8.0e-5
    b_gyr_cov: 3.18433768624e-6
    fov_degree: 180
    det_range:  150.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
    
    # vn100
    # extrinsic_T: [-0.057641264816183,  0.012413647990074, -0.020314659994286 ]
    # extrinsic_R: [ 0.999952473408854,  0.006268964451975, -0.007467423398803,
    #                0.006372805754146, -0.999882193502238, -0.013963622785029,
    #               -0.007379006587289, -0.014010548974605, -0.999874617971481 ]
    extrinsic_T: [ 0.0,  0.0,  0.0 ]
    extrinsic_R: [ 1.0,  0.0,  0.0,
                   0.0,  1.0,  0.0,
                   0.0,  0.0,  1.0]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
